export const ErrorCodes = {
    // Authentication Errors
    AUTH_401_UNAUTHORIZED: 'AUTH_401_UNAUTHORIZED',
    AUTH_403_FORBIDDEN: 'AUTH_403_FORBIDDEN',
    AUTH_404_USER_NOT_FOUND: 'AUTH_404_USER_NOT_FOUND',
    AUTH_409_USER_EXISTS: 'AUTH_409_USER_EXISTS',

    // Validation Errors
    VALIDATION_400_BAD_REQUEST: 'VALIDATION_400_BAD_REQUEST',
    VALIDATION_400_INVALID_INPUT: 'VALIDATION_400_INVALID_INPUT',
    VALIDATION_400_MISSING_FIELD: 'VALIDATION_400_MISSING_FIELD',

    // Resource Errors
    RESOURCE_404_NOT_FOUND: 'RESOURCE_404_NOT_FOUND',
    RESOURCE_409_CONFLICT: 'RESOURCE_409_CONFLICT',
    RESOURCE_410_GONE: 'RESOURCE_410_GONE',

    // Database Errors
    DB_500_DATABASE_ERROR: 'DB_500_DATABASE_ERROR',
    DB_409_DUPLICATE_ENTRY: 'DB_409_DUPLICATE_ENTRY',
    DB_409_FOREIGN_KEY_VIOLATION: 'DB_409_FOREIGN_KEY_VIOLATION',

    // Business Logic Errors
    BUSINESS_400_INVALID_OPERATION: 'BUSINESS_400_INVALID_OPERATION',
    BUSINESS_403_INSUFFICIENT_PERMISSION: 'BUSINESS_403_INSUFFICIENT_PERMISSION',
    BUSINESS_409_STATE_CONFLICT: 'BUSINESS_409_STATE_CONFLICT',

    // Payment Errors
    PAYMENT_402_PAYMENT_REQUIRED: 'PAYMENT_402_PAYMENT_REQUIRED',
    PAYMENT_400_INVALID_PAYMENT: 'PAYMENT_400_INVALID_PAYMENT',
    PAYMENT_409_ALREADY_PROCESSED: 'PAYMENT_409_ALREADY_PROCESSED',

    // Rate Limiting
    RATE_LIMIT_429_TOO_MANY_REQUESTS: 'RATE_LIMIT_429_TOO_MANY_REQUESTS',

    // Server Errors
    SERVER_500_INTERNAL_ERROR: 'SERVER_500_INTERNAL_ERROR',
    SERVER_503_SERVICE_UNAVAILABLE: 'SERVER_503_SERVICE_UNAVAILABLE',
    SERVER_504_GATEWAY_TIMEOUT: 'SERVER_504_GATEWAY_TIMEOUT',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
